# Generated by Django 2.1.1 on 2018-09-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=240)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Album')),
            ],
        ),
    ]
