# Generated by Django 2.1.1 on 2018-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
