# Generated by Django 2.1.1 on 2018-09-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_sign_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.CharField(max_length=50)),
                ('wine', models.CharField(max_length=50)),
            ],
        ),
    ]
